name: 'hello_world'
description: 'greet someone and record time'
inputs:
  who-to-greet: # id of input
    description: 'who to greet'
    required: true
    default: 'world'
outputs:
  time: 
    description: 'time we greeted'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - ${{ inputs.who-to-greet }}
